version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  build_and_test:
    docker:
      - image: circleci/node:14-browsers
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Install Playwright browsers
          command: npx playwright install
      - run:
          name: Run tests
          command: npm run test

workflows:
  test_my_app:
    jobs:
      - build_and_test
