version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install system dependencies for Playwright
          command: sudo npx playwright install-deps
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Install Playwright browsers
          command: npx playwright install
      - run:
          name: Run tests
          command: npx playwright test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
